version: '2'
services:
  shibboleth-fastcgi-build-centos-6:
    build:
      context: .
      dockerfile: ./configs/centos-6/Dockerfile
    volumes:
      - .:/app
  shibboleth-fastcgi-build-centos-7:
    build:
      context: .
      dockerfile: ./configs/centos-7/Dockerfile
    volumes:
      - .:/app
